services:
  - type: web
    name: treamis-club-selection
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase_key.json
    secrets:
      - source: firebase_key.json
        mountPath: /etc/secrets/firebase_key.json
